# Generated by Django 4.1.2 on 2022-11-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование чата'),
        ),
    ]
