# Generated by Django 4.1.2 on 2022-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chat_users_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_readen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
