# Generated by Django 4.1.2 on 2022-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_message_is_readen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_readen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Прочиатно'),
        ),
    ]
