# Generated by Django 4.1.2 on 2022-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_remove_chat_users_chat_created_at_chat_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateField(auto_now_add=True, verbose_name='Время отправления'),
        ),
    ]
