# Generated by Django 4.1.2 on 2022-11-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_visited',
            field=models.DateField(blank=True, null=True, verbose_name='Последний визит'),
        ),
    ]
